### ISSUE TITLE
Wallets endpoint - internal server error

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/core#1074]
**Describe the bug**

`api/v2/wallets/{id}` endpoint gives an internal server error

**To Reproduce**

1. Go to https://dexplorer.ark.io:8443/api/v2/wallets/D8wgoDnRNAW1tnjeTy5a39zMp8Wa3sJSFZ
2. Response will be a 500 error

**Expected behavior**

It should return the data of the corresponding address. Address exists on the blockchain as it can be seen here: https://dexplorer.ark.io/wallets/D8wgoDnRNAW1tnjeTy5a39zMp8Wa3sJSFZ

**Comment by ItsANameToo** [comment]
Seems that the whole `wallets` endpoint it down, as `api/v2/wallets` isn't working either

**Comment by supaiku0** [comment]
Yes, that's because `hapi-api-version` falls back to version `1` when no version is sent in the header. The endpoint handler then tries to call a transformer for the wallet object, but this is where it fails because there's no wallet transformer in the v1 api. So the main problem is that `request.pre.apiVersion` differs from the actual version of the endpoint.
