### ISSUE TITLE
Ark Commander updates the core but does not update the plugins.js

### ISSUE THREAD

**Issue by vaustymenko** [ArkEcosystem/core#1172]
**Describe the bug**
Ark Commander offers to update the core but it does not update the ~/.ark/plugins.js. As a result, if modules are removed in the core then relay/forger fail to start because they cannot find modules

**To Reproduce**
1. Launch Ark Commande
2. Select options to update core
3. Restart relay and observe logs
I saw things like 
1|ark-core-relay  | Error: Cannot find module '@arkecosystem/core-transaction-pool-redis'
1|ark-core | Error: Cannot find module '@arkecosystem/core-storage'

**Expected behavior**
Ark Commander must update the plugins.js, otherwise there is no point in updating the core

**Comment by faustbrian** [comment]
The `plugins.js` doesn't get updated because it can be touchy to do so, both because of people running modified configurations and having 3rd party plugins installed.

You as a node maintainer should know what runs on your server and what configuration is getting modified, it is also your responsibility as the maintainer to make sure your config is up to date with the latest changes as you shouldn't blindly update.

Also this issue should go to https://github.com/ArkEcosystem/core-commander

**Comment by vaustymenko** [comment]
@faustbrian I'll open the issues under core-commander
