### ISSUE TITLE
Handler:canApply can fail a transaction because of a case-sensitive check on publicKey

### ISSUE THREAD

**Issue by paroxysm** [ArkEcosystem/core#1252]
**Describe the bug**
crypto/lib/handlers/transactions/handler.js line 27.
There is  a comparison :
`applicable = (transaction.senderPublicKey === wallet.publicKey) && enoughBalance`

This check, will fail if either transaction.senderPublicKey is UPPERCASE and wallet.publicKey is lowercase or vice-versa, even if they're equal.
I ran into a scenario on my relay, where somehow the in-memory wallets found in Pool-Wallet-Manager(byPublicKey) became keyed by uppercase versions of the publicKey. So, on a subsequent transaction send, it would fail.
 This might have implications elsewhere where we do such comparisons.

**To Reproduce**
I'm not sure how the in-memory wallets got keyed in uppercase, but I'd start in the transaction-pool and dig there. At any case, that shouldn't cause the transaction to fail.

**Expected behavior**
The two properties are equal in meaning, but not in casing. That shouldn't be a deal breaker..

**Screenshots**
![uppercase_by_publickey](https://user-images.githubusercontent.com/2207711/47765633-e2063f00-dc98-11e8-898c-94ee4890dff5.png)

**Comment by faustbrian** [comment]
The easiest solution would be to add `setters` for those 2 properties.

```
set senderPublicKey(value) {
    this.senderPublicKey = this.senderPublicKey.toLowerCase()
}

set publicKey(value) {
    this.publicKey = this.publicKey.toLowerCase()
}
```

**Comment by paroxysm** [comment]
It's a good measure to put in the builders of all those objects. I did see that signature field was also uppercase and I'm wondering if that would cause an issue too.

We would still want to do a case-insensitive comparison in case there's places where we compose a transaction/wallet object w/o using their respective builders/constructors.

I'll work on trying to reproduce what causes this, but I can put up a PR for it.

**Comment by paroxysm** [comment]
@vasild @faustbrian I've found the root cause of this and it is indeed the transaction-mem-pool stuff. It happens when we're reading serialized transactions from the sqlite database.
![image](https://user-images.githubusercontent.com/2207711/47824767-6231b080-dd3c-11e8-95df-eb6b67e37f72.png)

According to the sqlite documentation https://sqlite.org/lang_corefunc.html#hex, returns the result in all uppercase.
So we can either do a 'toLowercase()' at 'loadAll', or we adopt the habit of converting to lowercase when comparing publicKeys, signatures, etc..
I feel like the latter is a more robust solution.

**Comment by vasild** [comment]
What a mess. The root of the problem is that we do machine operations on data that is presented in a human readable way, for humans to read, not machines.

Like, for example, trying to compare two dates by comparing their string representations and messing up trying to compare different human readable representations:
`Fri Nov 02 2018 08:20:40 GMT+0100 (Central European Standard Time)` toString() and
`11/2/2018, 8:20:40 AM` toLocaleString()
whereas the correct way would be to compare the machine readable variant (getTime() in this case).

That said, the correct way of doing things is to manipulate (store on disk, compare, send over the network) the public key in a binary buffer and only convert it to hex string when it is to be presented to humans. This way it will also take less space on disk, compare faster and use less bandwidth.
