### ISSUE TITLE
Implement core-cli to manage plugins and configuration

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1582]
This will be a CLI for core which should ultimately replace the bash commander.

**Comment by fix** [comment]
Can we somehow get a documentation page on the cli commands we would like to see? I think an AIP about this could be a good

**Comment by fix** [comment]
Because I expect this part take an increasing importance in the ark ecosystem:
- create sidechain
- monitor sidechain with statistics
- handle single node instances
- handle several relay front running forger, with backups.
- auditing node (txpool, blickchain state)
- trigger events in state machine.
