### ISSUE TITLE
Implement interfaces and abstract classes

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1783]
At the moment we have classes that are named like `ConnectionInterface`, using an `Interface` suffix to indicate that they have implementation expectations.

Those classes are actually `abstract` classes and should be refactored to behave like one. There are a few exceptions which are or should actually be `interfaces` that are implemented by other classes instead of extending an `abstract` class.

**Comment by paroxysm** [comment]
@faustbrian @kristjank @vasild 
I've hit a road-block with the ts typedefs PRs because going further would introduce circular dependencies. We have some awkward code where this happens.
i.e. core-blockchain references to core-transaction-pool & core-p2p in the methods `transactionPool` and `p2p` and some other places, but core-p2p & core-transaction-pool also reference the `Blockchain` type in core-blockchain.
`core-test-utils` has code that references `core-blockchain` types but it is itself a dependency of `core-blockchain`.
In order to proceed, there's TWO approaches we can implement.

1.  We can re-visit adn restructure these dependencies. i.e. Why does `core-utils` reference `core-blockchain` types when `core-blockchain` has `core-utils` as a dependency? We should move the code in `core-utils` that references `core-blockchain` into `core-blockchain`.
i.e. `core-blockchain` has a devDep on `core-p2p` because of its tests and even references core-p2p's `Peer` class. Yet `core-p2p` also references `core-blockchain` types. So why is `core-blockchain` testing components in `core-p2p`?

2. We start writing interfaces for all the concrete/abstract classes we have in our modules and package in ONE new module. i.e. `core-interface-types` or `core-interfaces`. 
This new module will be a dependency to the existing modules that will be implementing those interfaces. i.e. add a `export interface Blockchain {... }` in `core-interfaces` module then later in `core-blockchain` it provides a concrete implementation `export class BlockchainImpl implements Blockchain { ...}`. So that way, any class that needs the `Blockchain` type, will only need a dependency on `core-interfaces` module and only interact with the interface. The actual concrete implementation is only known to the module providing it, and with the DI we get with `core-container`, we still register concrete types.

I'm for approach 2 because it has the least friction. The tests in the modules already reference the interface names, we can replace with concrete types where needed. In addition, sourcing the types from the new module is a simple find-n-replace command away.
Before I proceed further with the other ts types PRs, I need this roadblock solved.

**Comment by faustbrian** [comment]
The least intrusive one for now is approach 2 but there is a far bigger issue with how types are currently done, which is why I in your initial types PR said it is OK for now but will need changes later on.

With how types are currently introduced and used all packages have to know about each others existents and exactly know which package provides the concrete implementations. The whole point of how packages have been structured so far is that this doesn't have to be the case, they only need to have the `core-container` package as a dependency and then resolve everything from there without the need of having another 20 dependencies for the packages that provide the concrete implementations.

Packages are bound to the container so plugins don't have any use for each other anyways as the instances that are useful to them are created in the `register` method that is called by the container. Exceptions to that rule are obviously the database packages as the postgres package `extends` the database package which provides all the base functionality that is required.

These kinda structural issues need to be addressed first as we otherwise defeat the purpose of the plugin system, which is to easily swap out components without having to spend days replacing code in another 20 packages.

**The general rule is that plugins should not require anything but `core-container` and helper packages like utilities.**

**Comment by faustbrian** [comment]
I don't think there is that much more overhead for maintaining type packages as they should rarely change in the future and if they do it won't be anything major. Versioning and publishing them is also a negligible amount of work as that will be automated.

_I am not home until the 1st of January but when I am back I will review a few things and look at what approach would be the simplest for now._ A plugin system rework is scheduled for 3.0 as I will be introducing a lot of breaking changes and resolve a lot of issues that were caused by how JavaScript works and enforce stricter contracts that need to be satisfied by plugins.

**Comment by paroxysm** [comment]
Fair enough, my concern w/  the @types package is that you're essentially forcing all changes(whether permanent or temp) to go through npm. From a development standpoint, this degrades the experience as modules cannot see any local changes to the types w/o having to first publish them to npm.
However,  if they end up being managed by lerna as a mono-repo package then that won't be an issue 👍

**Comment by faustbrian** [comment]
They would be managed in the same repository. I would restructure the repository to contain 3 folders that are managed by lerna as `essentials`, `optional` and `types`.

- `essentials` would be packages that are required to run a node like blockchain, pool, etc.
- `optional` would be packages like api, webhooks, etc.
- `types` would be packages that contain only the type defs

**Comment by paroxysm** [comment]
So, I thought about it some more, and even in their own types modules, you'd still have the circular dependency problem if your interfaces need to reference each other(method parameters or instance properties). If they're all in a single module, they can all see each other so it's all good, but if they're in different modules, the types modules would have to have dependencies on each other and you run into the same problem, introducing a circular dependency among the types modules.

The only way that would work is if the dependencies are realized(so `app.resolvePlugin<ImportedType>`) in the concrete implementation, not on the interface layer, i.e `interface Blockchain { get transactionPool() : TransactionPool }`. But that isn't a good approach because it restricts how you write your interfaces(to make sure you don't reference a type what would result in a circular dependency)
