### ISSUE TITLE
Split tests into functional, integration and unit

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1856]

**Comment by paroxysm** [comment]
This implies leveraging construction injection more than `app.resolve...`
In order to unit test a component, we need and should be mocking out all external components involved such that we're only testing the target component. For unit tests, we should not be relying on `app.resolve...` to inject dependencies, we should be passing them in via constructor.

We still retain the ability to construct the same components using real instances of their dependencies,
This unfortunately will break all the singleton components we define that require stuff from the DI container. At the moment, when we import that module, the component is instantiated. This is bad design because we do not have control of when or how we constructor the component.

I would argue, all the singleton objects be exported as lazy factory functions instead of  actual instances. We want to prevent eager creation of singletons that may require deps not yet initialized. i.e. a singleton that acquires an instance of ILogger, but the container hasn't finished loading that plugin yet.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/issues/1964
