### ISSUE TITLE
Batch database inserts when syncing

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core#1945]
Related to #1595 

We can make syncing much faster by batching block inserts (i.e only every 10k blocks).

Relevant functions:
https://github.com/ArkEcosystem/core/blob/12a6aa7cda7a5bb1d75448f09fe0305bced2cf75/packages/core-blockchain/src/blockchain.ts#L371
https://github.com/ArkEcosystem/core/blob/12a6aa7cda7a5bb1d75448f09fe0305bced2cf75/packages/core-blockchain/src/blockchain.ts#L417
https://github.com/ArkEcosystem/core/blob/12a6aa7cda7a5bb1d75448f09fe0305bced2cf75/packages/core-database-postgres/src/connection.ts#L337

**Comment by faustbrian** [comment]
@vasild put this as on top of your to-do list to get this done as soon as possible.

**Comment by vasild** [comment]
@supaiku0 do you mean to modify `saveBlock()` so that it does not touch the database at every invocation? That is - blocks stay in memory and occasionally (e.g. every 10k blocks) get saved into the database?

**Comment by faustbrian** [comment]
Yeah, right now we constantly dump blocks into the database as soon as we can. There used to be a "fast-sync" mode but that resulted in inaccurate data for the number of missed blocks as it would skip part of the sync process.

**Comment by vasild** [comment]
This looks quite dangerous to me - if the node crashes during sync this could leave the database in a corrupted state. I will look more into this - whether it is possible to leave the database in an outdated, but consistent state after a crash.

I wondered how much could we gain by such a batch optimization. I completely disabled `saveBlock()` and `enqueueSaveBlock()` to see what would be the theoretical maximum performance gain - if we don't touch the database at all:
```
diff --git i/packages/core-database-postgres/src/postgres-connection.ts w/packages/core-database-postgres/src/postgres-connection.ts
index 442a19eb9..f10cc43a9 100644
--- i/packages/core-database-postgres/src/postgres-connection.ts
+++ w/packages/core-database-postgres/src/postgres-connection.ts
@@ -136,19 +136,12 @@ export class PostgresConnection implements Database.IDatabaseConnection {
         if (nextRound === round + 1 && height >= maxDelegates) {
             this.enqueueQueries([this.roundsRepository.delete(nextRound)]);
         }
     }
 
     public enqueueSaveBlock(block: models.Block): any {
-        const queries = [this.blocksRepository.insert(block.data)];
-
-        if (block.transactions.length > 0) {
-            queries.push(this.transactionsRepository.insert(block.transactions));
-        }
-
-        this.enqueueQueries(queries);
     }
 
     public async make(): Promise<Database.IDatabaseConnection> {
         if (this.db) {
             throw new Error("Database connection already initialised");
         }
@@ -173,23 +166,12 @@ export class PostgresConnection implements Database.IDatabaseConnection {
         }
 
         return null;
     }
 
     public async saveBlock(block: models.Block) {
-        try {
-            const queries = [this.blocksRepository.insert(block.data)];
-
-            if (block.transactions.length > 0) {
-                queries.push(this.transactionsRepository.insert(block.transactions));
-            }
-
-            await this.db.tx(t => t.batch(queries));
-        } catch (err) {
-            this.logger.error(err.message);
-        }
     }
 
     public async saveWallets(wallets: any[], force?: boolean) {
         if (force) {
             // all wallets to be updated, performance is better without upsert
             await this.walletsRepository.truncate();
```

and tried to sync a database that is about 31k blocks behind the network. Got the following:
* Normal operation (db is enabled, current code): 5 min 04 sec
* Blocks don't hit the database at all (the above patch): 4 min 32 sec

So, the maximum improvement we could get is about 10%. In practice we would get less because we would have to save to database occasionally.

Thus, I wonder if it is worth diving into this.

> Before really embarking on a sizeable project, in particular before
> starting the large investment of coding, try to kill the project first.
>                 -- Edsger W. Dijkstra, EWD1308

**Comment by supaiku0** [comment]
Make sure it doesn't choke on the 400 blocks download limit. Looks to me like this is why you see no real difference.

`applyRound` also makes database round trips (`wallets` and `rounds` table).

**Comment by vasild** [comment]
> Make sure it doesn't choke on the 400 blocks download limit. Looks to me like this is why you see no real difference.

https://www.speedtest.net/result/8050203727
ping 17ms, download speed ~20Mbit/s - this should be good enough.
 
> `applyRound` also makes database round trips (`wallets` and `rounds` table).

I disabled `enqueueSaveBlock()`, `saveBlock()`, `saveWallets()` and `saveRound()`. Downloading ~34k blocks:
db enabled: 5 min 32 sec
db disabled: 5 min 01 sec
speed-up: ~9%.

To me this looks pretty expected. Have you done any tests yourself that show bigger speed-up?

**Comment by supaiku0** [comment]
What I mean is that the block downloads itself are now the bottleneck.

This is what currently happens when the db stuff is removed:
```
download 400 blocks
process queue is so fast it runs dry
download 400 blocks
process queue is so fast it runs dry
...
```
(You can see this when examining the logs)

Instead it should always have enough blocks in the queue so it doesn't dry up and ends up waiting for the next batch of blocks to arrive. That's why the perceived performance difference is nil.

**Comment by vasild** [comment]
Yes, I agree. Currently the download is the bottleneck. So, it does not make sense to blindly try to optimize this. Blindly because the targeted performance boost will not be observed. This should be done after we have parallel block downloads. @faustbrian 

By the way, while looking at the code around this, it struck me that even now, in the event of abnormal termination, the database will be left in an inconsistent state. Each table is inserted into (or updated) in a separate transaction. The database layer needs some refactoring. Is removing PostgreSQL on our TODO, replacing it with an embedded database, like sqlite, leveldb or something else that requires zero configuration or maintenance from the user?

**Comment by faustbrian** [comment]
Not at the moment, probably best to do after 2.6 as we will remove all v1 code which will already get rid of a lot of garbage but we used to use http://docs.sequelizejs.com/ which had support for SQLite but the overall performance was atrocious.

Another issue was that nodes would constantly run into dead-locks with SQLite during the sync and I was able to make nodes miss blocks on purpose or cause them to go out of sync because of those deadlocks.

_If, and only if, those issues can be 100% resolved I would support a move from PostgreSQL to an embedded database as it also means less dependencies that need to be installed on a system._

**Comment by vasild** [comment]
Yes, I think that is doable. What has been missing before is an intermediate caching layer like the one described in https://github.com/ArkEcosystem/core/issues/2114 and similar to the one we have now in the transaction pool. With that, the on-disk database is only touched occasionally and the only downside is that, in the event of an abnormal shutdown, the node will go back to a state it was e.g. 5 minutes ago (or the last time data was synced to the permanent storage/disk). Which is acceptable.

**Comment by faustbrian** [comment]
I've moved this task to `2.7.0` together with WebSockets and parallel downloads as all those things combined will have the biggest impact on sync performance.

@vasild when your current tasks are done you can work on an embedded database like SQLite if you want as that will save us time refactoring the `core-database-postgres` package more then we are already doing.

**Comment by paroxysm** [comment]
@vasild @faustbrian  We could write a transaction creating/committing service whose implementation is database-specific.
Typescript supports annotations; we can write an annotation that would be applied on methods that are expected to execute in a transaction.
The code behind the annotation will invoke the TX Service to create a database-specific(maybe even support nested) TX.
Then we modify the code that's executing sql queries to check with the transaction service to see if we have a TX(if we need to use a TX that is), and use it.
Then afterwards, the TX service will also commit the transaction.

So i.e. the delete block method deletes both the block and the transactions associated with it, and these two operations should be executed in a transaction.

If you annotate the "deleteBlock" business method, a postgres specific TX is created by the TX service. Then, at the db-repo layer, rather create a new TX, it checks with the TX Service to see if there's an existing one and use that.

Then after "deleteBlock" is finished, the TX service automatically commits that TX.
Alternatively, the TX service can also rollback that TX in the event of an exception or error.
