### ISSUE TITLE
Timestamp based sorting not working reliably

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/core#1951]
**Describe the bug**
The sorting based on timestamp does not work reliably, resulting in an un-ordered result from the API, v1 and v2 endpoints are affected.

**To Reproduce**
1. https://explorer.ark.io:8443/api/v1/transactions?senderId=AcNiPbV1XZ7wkFwoBD3NjpSGFEkyohYLER&orderBy=timestamp:desc
2. Pick and search for a timestamp, e.g. `56757607`

**Expected behavior**
A well sorted list of transactions.

**Screenshots**
![image](https://user-images.githubusercontent.com/6547002/50770392-72f42a80-1287-11e9-87c5-07278dfd6feb.png)

**Comment by faustbrian** [comment]
There seems to be another issue with the timestamps. https://explorer.ark.io:8443/api/v1/transactions/get?id=0511e54fedbc0cb9e14bfa2442a55baddd73146dc1282929ad03921bbd62cb39

That transaction for example shows a timestamp of `56844008` but when I do an sql query for that transaction directly on my server it shows a timestamp of `56844058`, ending with `58` instead of `08`.
