### ISSUE TITLE
Implement fast in-memory database with JSON storage

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1963]
Things like the transaction pool could greatly benefit from a fast in-memory storage that could fallback to store everything in a JSON file for which we then could use fast.js to do very fast queries on objects rather then a database as the pool itself doesn't contain any relational data.

Something like https://github.com/typicode/lowdb but a faster implementation because lowdb uses lodash which is rather fat and slow.

**Comment by vasild** [comment]
Currently we store the transactions in the transaction pool in memory in a quite efficient way. It is more involved than the following, but to illustrate, we use:
```
byId = {}
byId[tx1id] = tx1
byId[tx2id] = tx2
...
// and to retrieve:
byId[someId]
```
This has `O(1)` complexity. I can't imagine something more efficient without implementing it in native code (C++).

Our on-disk storage (which is engaged occasionally) is [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science)) compliant. Or in lame's terms, it is crash safe.

That said, there is always room for improvement (for example https://github.com/ArkEcosystem/core/blob/develop/packages/core-transaction-pool/src/mem.ts#L156), but any changes would better be well justified and tested in order to avoid performance regressions.

**Comment by faustbrian** [comment]
Ditching in favour of https://github.com/ArkEcosystem/core/issues/2114.
