### ISSUE TITLE
jest collect coverage from /dist/**/*.js instead of /src/**/*.ts

### ISSUE THREAD

**Issue by paroxysm** [ArkEcosystem/core#1977]
**Describe the bug**
Right now in the tests, we're doing a mix-match of `import {..} ../src/...` and `import {..} ../dist/..`
The issue with the latter is that jest coverage is set to collect from `src/**/.ts`.
Except, there's a very subtle and nasty bug when tests import from `src` folder. 
The state of objects that are instantiated upon module import. 
I ran into this hair-pulling bug in `core-blockchain/src/plugin.ts` and also in `core-p2p/src/plugin.ts`

line 4: `import { config } from "./config";`
line 19: `        config.init(options);`

`./config` instantiates a config object when that module is loaded. Now here's the kicker.
Doing `import {config} from "/src/config"` counts as a different module, when compared to `import {config} from "/dist/config"`

If ANOTHER class imports the `./config` module, the `./config` shares its path too. 
So if you import a class with from `/src/` then the `./config` module will be loaded from `/src/config`.
 If you import from `/dist`, the `./config` is loaded from `/dist/config`

Why is this an issue?
The tests were importing & loading the tested class from `src`, but the jest-runner was booting up and loading classes from `dist` .
Because those two are considered different paths/modules, **they will each new up a config object resulting in two instances of the Config class**. 
However, when later in line 19 shown above, only the config instance created by code running from `/dist` will have the `.init` method called on it. The `src` config instance will not.
This creates a very peculiar issue where the tests will fail because, the config instance the tests refer to, hasn't been initialized and the tests were expecting that behavior.

So we change the tests to import from `dist`, but now we get no coverage because jest is looking at `src` source files.

Since we can't force jest-runner to boot from `src`, tests should be referencing `dist` imports(which are supposed to be the compiled sources anyway so it's appropriate for tests to refer to them), we should change where jest is looking for coverage to `dist/**/*.js`.
Solves both that bug, and we still get the coverage numbers, while losing readability since coverage will be based on the transpiled files, which aren't always human-readable.

**Comment by paroxysm** [comment]
Wasn't able to reproduce this as before(probably due to core-blockchain/index.ts code being moved to core-blockchain/plugin.ts)

**Comment by paroxysm** [comment]
Coincidentally, this discrepancy on where we import from explains why core-api coverage isn't correct. When I run a single test in core-api, my ide shows ZERO coverage percentage. 
However, when I modify ./jest-preset.json, to include `dist/**/*.js` to the list of places to collect coverage from, it jumps to 51%. So core-api tests are testing components from the `dist` instead of the `src` folder

**Comment by air1one** [comment]
Hey thanks for the analysis I also ran into this coverage issue before but didn't figure out what was wrong, now I think I understand better.
So you're right it's like we have 2 distinct applications : the one that's generated in `dist` and the one in `src` and for tests there is a mess between the two.

For testing we use `ts-jest` typescript pre-processor (not `tsc`), so ideally this would allow us to just run the tests without caring of anything generated in `dist` (because it would automatically take care of typescript compilation on the fly).
But right now I think what's happening is : 
- `ts-jest` compiles "what he can" from the test files and the config we provided
- and we also have the `dist` folder with everything generated
So as we use `ts-jest` as typescript pre-processor for tests, when at some point we call the application in `dist`, it's like we call a totally different application and then of course coverage is not recorded because we didn't hit "our" application (the one `ts-jest` compiled).

I don't know if that makes sense ? :smile: 

So to me the solution here is to make a choice : either we compile everything with `tsc` including tests, either we use `ts-jest` but it has to be correctly configured and work without `tsc` compiled files in `dist`.

Anyway I think we should never `import from "dist/...".

**Comment by vasild** [comment]
What a mess!

@paroxysm, thanks for the analysis, a valuable one! I have two questions:

> This creates a very peculiar issue where the tests will fail because...

Why don't we see any failures on circleci when run on pull requests? For example: https://circleci.com/gh/ArkEcosystem/core/10411?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

> we still get the coverage numbers, while losing readability since coverage will be based on the transpiled files, which aren't always human-readable

Coverage on generated files - nearly useless. If I am to do that, then I would rather drop the whole idea and not bother with collecting coverage at all. Just imagine trying to write a test to cover some line in the generated file (.js) that does not have a clear counterpart in the the source code (.ts). Or just trying to see which lines are covered and which not in the source code (.ts) by looking at coverage for generated files (.js).

> Anyway I think we should never `import from "dist/...".

I agree!

I am thinking - we can't be the only ones running into this problem. Must be happening to everybody who uses TypeScript and tries to collect coverage, right?

**Comment by paroxysm** [comment]
@vasild You're not seeing the failure in circleci because the code I screen-shotted above is local to me.
If you look at the [monitor.test.ts](https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/__tests__/monitor.test.ts) that's currently on `develop` branch, it's importing from `/dist/peer` which is not the approach we want, but yet allows the tests to pass.

The files in `dist` represent the transpiled code. The code that we ACTUALLY run live. I don't have an issue with writing tests that target the code we actually run. @air1one pointed out a suggestion which would be to also compile the tests with tsc and run them as .js files instead of .ts. That still won't work because the tests are in a different folder and in order to reference the components for testing, we still have to decide whether to pull them from `src` or `dist`.

the jest-runner will always bootstrap the code from `dist`, not `src`. As it should too, because when we're exporting our modules, we say export stuff from the `dist` folder, we don't export stuff in the `src` folder.
So this will always be an issue if we keep importing from `src`.

**Comment by supaiku0** [comment]
Thanks for the analysis! Because of this problem, we had to resort to some hacks when we ported to TypeScript:

https://github.com/ArkEcosystem/core/blob/5a703df3c2b1f86a7e25a7d39fb2334af4d7b436/packages/core-database/src/wallet-manager.ts#L23-L25
(deferring the resolve calls by moving it to the constructor)

Otherwise it will resolve to undefined when imported at module scope when imported (explicitely) in a unit test, because of the phenomen you described.

Anyway, what I came here for:
> Anyway I think we should never `import from "dist/...".
:+1:

**Comment by air1one** [comment]
Thanks guys for your answers. After some more investigation I think I have a solution that can make everyone happy :

Basically when we are in a package, say core-api, we just register manually the core-api plugin. This gets us typescript coverage.

Why does this work ? Because when we register manually our package, we will register the code that is transpiled by `ts-jest` and as this is the typescript pre-processor we use for tests it works fine.

Right now we let core-container register automatically all the packages, so basically when we're in core-api, it registers the core-api code that's in `dist` and that has nothing to do with the code we're actually transpiling at the moment (again, this one is transpiled by `ts-jest`). Hence the coverage issue.

I tested on core-api package and got coverage with my solution. I will prepare a pull request and update the other packages, so you can see what I'm talking about 👍

**Comment by paroxysm** [comment]
@air1one, that may work, but only if all the components being tested are local to the package. If core-api is importing code from other modules, that code will be loaded that modules `dist` folder, not `src` respectively. 
Why? Because that's what we're exporting, if you look at every package.json of each of our modules.
Therefore, you'd still have some strangeness where some components are loaded from `src` and some are `dist`. Whether or not they will conflict with each other is something that needs to be investigated and tested against.

That test in core-p2p, `monitor.test.ts` demonstrates the issue with importing from `src` instead of `dist`. If your method is to work, verify it with that first.

**Comment by air1one** [comment]
Yeah agree with you @paroxysm : when we are for example in core-api and we
`import {} from "@arkecosystem/core-transaction-pool"`
this is imported from core-transaction-pool `dist` folder, which is ok. In this case if we call things in transaction-pool, we will not have coverage for transaction-pool. This is fine to me because we are testing core-api, if we want transaction-pool to have coverage we write tests in its package.

To clarify what I'm against is writing `import from "dist"`. I prefer `import from "@arkecosystem/package"` even if this refers to `dist` : and in this case we just make the package export what is needed.
But when we're inside a package and want to import from the same package, we should import from its `src`. (for code and for tests)

**Comment by paroxysm** [comment]
I agree @air1one , I don't like importing from `dist` either. But if this doesn't work, we'll have to find an alternative solution that isn't import from `dist`. But I can already foresee such a solution leading to architectural changes throughout the code-base

**Comment by faustbrian** [comment]
https://codecov.io/gh/ArkEcosystem/core/tree/develop/packages
