### ISSUE TITLE
feat: improve IP filtering scheme (p2p layer) 

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#2089]
Introduce IP-Filtering, based on sublogic to detect same IP-Range attack. IF filtering based on range-similar IPs filtering. The process is similar to the one present in BitCoin. 

If we detect a large number of same IPs (x.y.0.0) where the first x.y. are the same  - they are blocked, and we only use 3-5 nodes from that subnet list.

Realization:
- [ ] Introduce two lists of Peers (Known Peers and Consensus Peers for PBFT)
- [ ] Add peer trust rules to consensus (after being present with no errors for S height). S is the same constant as in the moving checkpoint rebuild limit. 

A peer is in consensus list IF:
  - not in IP range cluster (filter rule)
  - after being present for XX height with no errors

Similar to Bitcoin: https://en.bitcoin.it/wiki/Weaknesses#Sybil_attack

**Comment by vasild** [comment]
Prerequisite:
Alter the consensus algorithm to not use the state of *all* nodes in the network (and calculating a quorum of 66%). Because, obviously, the 66% quorum calculations would be skewed if we only talk to a subset of the nodes in the network.

Also, the proposed change will kick some of the peers in https://raw.githubusercontent.com/ArkEcosystem/peers/master/mainnet.json. That list may need to be diversified.

**Comment by geopsllc** [comment]
3-5 is too low a number considering you're talking about a /16 filter which could be a whole datacenter where many host their nodes. 3-5 will be OK for a /24 filter.
