### ISSUE TITLE
/api/transactions/search to handle search by recipient from multipayment recipients

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3741]
`POST /api/transactions/search` currently doesn't support to search multipayment tx by recipients since the recipients sit in the asset of the multipayment transaction.

**Comment by rainydio** [comment]
Okay. But as an alternative I can also enable OR condition for search endpoints, so that multipayment can be included like this:

```json
[
  { "recipientId": "<recipient address>" },
  { "asset": { "payment": { "recipientId": "<recipient address>"  } } }
]
```

Or I can add additional aggregated criteria property:

```json
{ "anyRecipientId": "<recipient address>" }
```

Otherwise it isn't clear why transactions that are included into result may have unexpected recipientId that doesn't match specified criteria (because asset.payment.recipientId does).

**Comment by air1one** [comment]
Yeah OR could be good, what do you think @faustbrian ?

**Comment by faustbrian** [comment]
Not really a fan of that because we don't require special recipient types to be specified for anything else and that just makes it more tedious to retrieve transactions.

When you request transactions via API without a `type` or `typeGroup` filter your expectation would be that you get all transactions that could have a `recipientId` without thinking about what type the transaction is.

Also, this has to work with the `addresses` parameter which can be used to look up transactions for multiple addresses at the same time.

**Comment by rainydio** [comment]
Not gonna fight for it

**Comment by rainydio** [comment]
- `recipientId` now searches through multipayment too
- added `address` criteria to filter by either `recipientId` or `senderId`
