### ISSUE TITLE
`multipleResolves` log message

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3881]
We get a log message right after forging that looks like this : 
```
0|core  |  ℹ  multipleResolves (a promise was resolved multiple times) 
0|core  | Initially resolved with: [
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined, undefined, undefined,
0|core  |   undefined, undefined
0|core  | ]
0|core  | Then resolved again with: undefined
```

We need to investigate and fix the issue.

**Comment by sebastijankuzner** [comment]
The message is caused by Promise.race in:

 https://github.com/ArkEcosystem/core/blob/56b46716e250ea0021e9172559ddd42b44dc4fcb/packages/core-p2p/src/network-monitor.ts#L158-L182

Nothing unusual is happening, because race method is causing "multipleResolves" events as described in [nodejs docs](https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_event_multipleresolves). We are also logging all process errors with [log-process-errors package](https://www.npmjs.com/package/log-process-errors).
