### ISSUE TITLE
P2P socket termination errors

### ISSUE THREAD

**Issue by bertiespell** [ArkEcosystem/core#3883]
**Expected Behavior**

When peer-A terminates a socket connection with peer-B, then peer-B should log message once and move on.

**Current Behavior**

This bug was discovered when attempting to sync v3 with devnet (with two v3 peers connected). When peer-A terminates a socket from peer-B, the following error continues to log, and appears to block node from moving on:

`DEBUG: Socket error (peer 127.0.0.1) : Connection terminated while waiting to connect`

**Steps to Reproduce (for bugs)**

- Connect peer A
- Connect peer B
- Terminate socket from A
- Notice repeated errors in B

**Comment by sebastijankuzner** [comment]
Log is present, because peer is still in the list of known peers. In my opinion it is good behavior, if node tries to connect to another peer multiple times and log every time the connection was not successful. 

@air1one  Maybe we can just remove the peer after some time if it is not responding of after x attempts to reconnect. In other way the nodes from peer list defined in configurations can always stay in the list.

**Comment by air1one** [comment]
Yeah I agree @sebastijankuzner let's remove the peer after X attempts to reconnect. 2 or 3 attempts should be enough to give up and remove the peer :thinking:
