### ISSUE TITLE
AIPS16 - minAcceptableFee is not used anymore

### ISSUE THREAD

**Issue by iElsha** [ArkEcosystem/core#4364]
**Expected Behavior**

 Based on [AIPS 16](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-16.md), the method `dynamicFeeMatcher` should check, in case of dynamic fees, that the fee is higher than `minAcceptableFee` set by the delegate in his `delegate.json` config file (calculated with `feeMultiplier` as `satoshiPerByte` parameter).

**Current Behavior**

The method `dynamicFeeMatcher` is not using the parameter `minAcceptableFee` to check if the delegates want to forge the transaction or not. It properly check for `minFeeBroadcast` and `minFeePool` but not for `minAcceptableFee`.

**Last usage**

I saw that this parameter was used here packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js, before the TS migration, but hasn't been added back.

**Your Environment**

- Version used: develop branch

**Your question**

Is that normal that these feature has been disabled? If so has it been documented as I couldn't find anything on it?

**Comment by rainydio** [comment]
`minAcceptableFee` isn't isn't used in 2.x. Implementing it isn't trivial. The difficult part is to ensure that transaction isn't gonna bounce forever. Node has to keep list of recent transactions that it already broadcasted. Otherwise continuously re-sending transaction with fee lower than `minAcceptableFee` can be used to drain `postTransactions` rate limits of whole network. 

It will be implemented later.
