### ISSUE TITLE
Error: Cannot apply a transaction with nonce 1

### ISSUE THREAD

**Issue by Moisey777** [ArkEcosystem/core#4446]
Hello, I am trying to send my token to another wallet, and it gives me an error. I used deployer-v2 to install a blockchain on ubuntu 20.04 without vagrant.
I have logged into my genesis wallet and cannot send tokens, I tried on the desktop and mobile versions.
```
ransaction d908741186a44d1d79b74322a87ac61ae9db4ab25e29275bd41b0ea2c95aedd6 eligible for broadcast and to enter pool - fee of 0.1 MT is equal to static fee (0.1 MT)
0|mytest-relay  | [2021-07-17 15:02:25.134] ERROR: [Pool] Cannot apply a transaction with nonce 1: the sender 02190df9f0a7578dbc6c60a2da1bdaa112e131b74f18703442cc3f8a9c32634b72 has nonce 1.
0|mytest-relay  | [2021-07-17 15:02:25.134] DEBUG: {"d908741186a44d1d79b74322a87ac61ae9db4ab25e29275bd41b0ea2c95aedd6":[{"type":"ERR_APPLY","message":"Cannot apply a transaction with nonce 1: the sender 02190df9f0a7578dbc6c60a2da1bdaa112e131b74f18703442cc3f8a9c32634b72 has nonce 1."}]}
0|mytest-relay  | [2021-07-17 15:02:25.135] INFO : Received 1 transaction (accept: 0 broadcast: 0 excess: 0 invalid: 1).
```

**Comment by sleepdefic1t** [comment]
@Moisey777 

> `Cannot apply a transaction with nonce 1: the sender 02190…34b72 has nonce 1`

Did you try using a nonce of `2`?

**Comment by sleepdefic1t** [comment]
p.s. A wallet send is always current nonce + 1.

[https://ark.dev/docs/core/transactions/understanding-the-nonce](https://ark.dev/docs/core/transactions/understanding-the-nonce)

**Comment by Moisey777** [comment]
well I reinstalled the core and that works now

**Comment by sleepdefic1t** [comment]
Thank you for the follow up here, @Moisey777 👍

---

To help clarify and document this for future reference..

This was a custom chain’s Testnet installation configured via ‘**Deployer**’.

At some point, it appears the ‘**relay**’ process went M.I.A. causing the ‘**forger**’ process to restart.

Upon restart, the ‘**forger**’ process was missing the `--ignoreMinimumNetworkReach` flag which allows a Testnet to forge without the need for active peers.

With the network being unable to forge, the user’s 1st transaction attempt (_nonce of **1**_)  was stuck in the transaction pool.
 
Since a wallet’s state—as reported via Public API—does not consider pooled transactions, it was reporting the user’s current nonce as **0**.

This resulted in subsequent transaction attempts from the user’s wallet (_still nonce of **1** per API_) being rejected as the transaction pool expected the user’s next transaction to have a nonce of **2**.
