### ISSUE TITLE
IPFS CIDv1 not supported by the ipfs transaction type

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/core#4626]
Schema and ser/der only supports the old CIDv0 format.

https://docs.ipfs.io/concepts/content-addressing/

**Comment by sebastijankuzner** [comment]
We currently only support CIDv0. Adding support for CIDv1 is currently not planned because it drastically changes behavior. We cannot change the existing transaction type and stay on the same version. The proposed change requires a completely new version of the transaction. Full support for CIDv1 is currently not planned due to its complexity.
