### ISSUE TITLE
Taking over the ark Rust crate on crates.io

### ISSUE THREAD

**Issue by DavisVaughan** [ArkEcosystem/core#4829]
Hi there,

I am part of the ark development team:
https://github.com/posit-dev/ark

We have built a Jupyter kernel, language server, and debug adapter for R, all in Rust.

We'd like to own the ark crate on crates.io:
https://crates.io/crates/ark/

We see that a member of the ark blockchain community owns it. I have opened this issue, but they have been inactive for a long time so I'm not super hopeful about getting a response directly https://github.com/nalbech87/rust-ark/issues/3. Do any of you know this person? And would it be possible to get in contact with them somehow?

Thanks!
Davis

**Comment by ItsANameToo** [comment]
Hi @DavisVaughan ,

Thank you for reaching out. Unfortunately, we don't have any direct contact information for the person behind that crate and are not aware of anyone who may know them personally.

Best of luck with your project, and hopefully you manage to get the crate!

**Comment by DavisVaughan** [comment]
Thanks @ItsANameToo. One last question, in your opinion, does it look like the content in that crate would successfully run against the current version of the ark api? Or is it woefully outdated and dead?

I guess I'm asking about files like this in particular, and whether these target anything "real" anymore:
https://github.com/nalbech87/rust-ark/blob/11d5d69152f7f433f4af8d53682f46261ef1be55/src/manager/manager.rs#L18

**Comment by ItsANameToo** [comment]
It will be outdated and created against the initial ARK core version; seeing the last commit is from 7 years ago. Since then we've had a v2 and v3 (current) release, which bring breaking changes to the API. You can for example compare the response it expects for the blocks endpoint here https://github.com/nalbech87/rust-ark/blob/11d5d69152f7f433f4af8d53682f46261ef1be55/src/models/block.rs#L12 against the current response https://api.ark.io/api/blocks?limit=1 .

The URL you linked specifically is also no longer in use. I'm not even sure if that was an official URL or one hosted by a community member

**Comment by DavisVaughan** [comment]
Thank you!
