### ISSUE TITLE
Fix 'deregister plugins' test

### ISSUE THREAD

**Issue by paroxysm** [ArkEcosystem/core#769]
**Describe the bug**
The de-register plugins tests fails because it's written erroneously. Awilix doesn't appear to have a concept of "removing" an instance once you register it(w/o tearing down the entire thing). However, since we're interested in making sure the deregister function of a plugin is called(or not called if not set), we can sufficiently test this via jest mock fns.

**To Reproduce**
modify plugin.test.js to run "tearDown"(it's currently ignored)

**Expected behavior**
Test should pass

**Comment by faustbrian** [comment]
Awilix doesn't really matter in the context of the deregister method as the purpose of it has nothing to do with removing a plugin from the container at runtime but rather shutting down plugin specific instances like hapi.js servers which are mounted by API plugins that otherwise could cause things like `ERRADDR already in use` when you shutdown core and want to restart it.

Nonetheless, the previous tests were still wrong so thanks for that PR.

**Comment by paroxysm** [comment]
Agreed, then it might be better to change how the PluginRegistrar discovers plugins in a way that can be tested independently(and subsequently mocked out). This makes it easier for the test itself to define the plugins it wants to register(rather than having them in a file), that way the test doesn't have to go thru the awilix container to get a reference to assert against
