### ISSUE TITLE
Peer banned on fork

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#853]
**Describe the bug**
Currently a peer is banned when downloading a block that is refused. I don't think this should happen because that peer could be on the correct chain, and i'm the one that needs to rebuild. The line in question is https://github.com/ArkEcosystem/core/blob/master/packages/core-blockchain/lib/state-machine.js#L309

**To Reproduce**
Begin syncing a forging node with the chain. Once established a few rounds, stop the node and then run in test mode (`ARK_ENV=test ./bin/ark start ...`). This will forge on its own chain (it has to be a forging node). Make sure LESS THAN 51 blocks are forged, then stop the node and start forging on the chain again (without `ARK_ENV=test`). If the node tries downloading blocks (which it should), the block will be refused at the peer banned.

**Expected behavior**
The node should try a different peer, and do so until it establishes it has forked.

**Screenshots**
![image](https://user-images.githubusercontent.com/8069294/44006712-cb63cfac-9e80-11e8-83a2-ff26a932dd82.png)

**Server (please complete the following information):**
 - OS: MacOS
 - Version: High Sierra (10.13.3)

**Additional context**
In my case I am running a 5 forger, 2 node setup. I believe the issue to still apply here.

**Comment by magmel48** [comment]
is there any update here? My node cannot fetch any block, seems like all peers banned

**Comment by faustbrian** [comment]
Are you on devnet?

**Comment by magmel48** [comment]
nope, I used mainnet and in logs I had:

[inf] 2018-10-12 10:10:25 | http://5.39.53.54:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://5.39.53.55:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.160:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.161:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.162:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.163:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.164:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.165:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.166:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.167:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.168:4001 banned for 360 minutes
[inf] 2018-10-12 10:11:25 | http://5.39.53.51:4001 banned for 360 minutes
...

because of that I could not receive incoming payments and my node was out of sync.

**Comment by faustbrian** [comment]
Your issues are related to https://github.com/ArkEcosystem/ark-node. This repository is v2 which is still under development and not yet on mainnet.

**Comment by magmel48** [comment]
thank you, created this one https://github.com/ArkEcosystem/ark-node/issues/120
